# Generated by Django 5.2.1 on 2025-05-13 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_product_image_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
